using System.Collections.Generic;

namespace AgentUsageObserver.Services.Localization;

/// <summary>
/// Keys for all visible UI strings.
/// </summary>
public enum Str
{
    AppName,
    UnexpectedError,

    WindowConfigTitle,
    SettingsHeader,
    SectionRefresh,
    PollIntervalLabel,
    PollIntervalHint,
    SectionIconColors,
    UseServerSeverity,
    UseServerSeverityHint,
    WarnFromLabel,
    CritFromLabel,
    SectionSystem,
    StartWithWindows,
    ButtonClose,
    ButtonSave,

    MiniPanelTitle,
    StatusNoSession,
    StatusNoConnection,
    StatusRateLimited,
    MsgSignIn,
    MsgCouldNotFetch,
    MsgRateLimitReached,
    Updated,
    OpenSettingsLink,

    LabelFiveHour,
    LabelWeek,
    ResetsSoon,
    ResetsInDays,
    ResetsInHours,
    ResetsInMinutes,

    TrayStartupTitle,
    TrayStartupMessage,
    TooltipLoading,
    TooltipNoSession,
    TooltipNoConnection,
    TooltipFiveHour,
    TooltipFiveHourEmpty,
    TooltipWeek,
    TooltipWeekEmpty,
    TooltipWaiting,
    MenuSettings,
    MenuRefreshNow,
    MenuExit,

    ProviderSignInClaudeCode,
    ProviderSignInCodex,
    ProviderSessionExpired,
    ProviderRateLimitRetry,
    ProviderUsageQueryError,
    ProviderNoConnection,
    ProviderNoRecentUsageData,

    WaitSeconds,
    WaitMinutes,
    WaitHours,

    UpdateAvailableTitle,
    UpdateAvailableMessage,
    UpdateButtonInstall,
    UpdateButtonLater,
    UpdateButtonSkip,
    UpdateDownloadError,
}

/// <summary>
/// Translation tables. English is the fallback and must stay complete.
/// </summary>
public static class Strings
{
    public static readonly IReadOnlyDictionary<Str, string> En = new Dictionary<Str, string>
    {
        [Str.AppName] = "Agent Usage Observer",
        [Str.UnexpectedError] = "An unexpected error occurred:\n\n{0}",

        [Str.WindowConfigTitle] = "Agent Usage Observer",
        [Str.SettingsHeader] = "Settings",
        [Str.SectionRefresh] = "Refresh",
        [Str.PollIntervalLabel] = "Query interval: ",
        [Str.PollIntervalHint] = "How often usage is queried from providers (60 to 900 s). Increasing this avoids unnecessary polling.",
        [Str.SectionIconColors] = "Icon colors",
        [Str.UseServerSeverity] = "Use the severity reported by the server",
        [Str.UseServerSeverityHint] = "When enabled, the provider decides the color; otherwise the thresholds below are used.",
        [Str.WarnFromLabel] = "Yellow from: ",
        [Str.CritFromLabel] = "Red from: ",
        [Str.SectionSystem] = "System",
        [Str.StartWithWindows] = "Start with Windows",
        [Str.ButtonClose] = "Close",
        [Str.ButtonSave] = "Save",

        [Str.MiniPanelTitle] = "Agents",
        [Str.StatusNoSession] = "no session",
        [Str.StatusNoConnection] = "no connection",
        [Str.StatusRateLimited] = "limit reached",
        [Str.MsgSignIn] = "Sign in to the provider.",
        [Str.MsgCouldNotFetch] = "Could not fetch usage.",
        [Str.MsgRateLimitReached] = "Usage limit reached.",
        [Str.Updated] = "Updated {0}",
        [Str.OpenSettingsLink] = "Open settings",

        [Str.LabelFiveHour] = "Last 5h",
        [Str.LabelWeek] = "Week",
        [Str.ResetsSoon] = "Resets soon",
        [Str.ResetsInDays] = "Resets in {0}d {1}h",
        [Str.ResetsInHours] = "Resets in {0}h {1}m",
        [Str.ResetsInMinutes] = "Resets in {0}m",

        [Str.TrayStartupTitle] = "Agent Usage Observer",
        [Str.TrayStartupMessage] = "Monitoring agent usage. Look for the icon in the notification area (^ arrow).",
        [Str.TooltipLoading] = "Agent usage loading...",
        [Str.TooltipNoSession] = "No session",
        [Str.TooltipNoConnection] = "No connection",
        [Str.TooltipFiveHour] = "5h {0}%",
        [Str.TooltipFiveHourEmpty] = "5h -",
        [Str.TooltipWeek] = "Week {0}%",
        [Str.TooltipWeekEmpty] = "Week -",
        [Str.TooltipWaiting] = " - waiting",
        [Str.MenuSettings] = "Settings...",
        [Str.MenuRefreshNow] = "Refresh now",
        [Str.MenuExit] = "Exit",

        [Str.ProviderSignInClaudeCode] = "Sign in to Claude Code (claude login).",
        [Str.ProviderSignInCodex] = "Sign in to Codex.",
        [Str.ProviderSessionExpired] = "Claude session expired. Reopen Claude Code.",
        [Str.ProviderRateLimitRetry] = "Query limit reached. Retry in {0}.",
        [Str.ProviderUsageQueryError] = "Error querying usage ({0}).",
        [Str.ProviderNoConnection] = "No connection to api.anthropic.com.",
        [Str.ProviderNoRecentUsageData] = "No recent Codex usage data found yet. Start a Codex session.",

        [Str.WaitSeconds] = "{0} s",
        [Str.WaitMinutes] = "{0} min",
        [Str.WaitHours] = "{0} h",

        [Str.UpdateAvailableTitle] = "Update available",
        [Str.UpdateAvailableMessage] = "A new version is available: {0} (you have {1}).\n\nDownload and install it now?",
        [Str.UpdateButtonInstall] = "Install now",
        [Str.UpdateButtonLater] = "Later",
        [Str.UpdateButtonSkip] = "Skip this version",
        [Str.UpdateDownloadError] = "Could not download the update:\n\n{0}",
    };

    public static readonly IReadOnlyDictionary<Str, string> Es = new Dictionary<Str, string>
    {
        [Str.AppName] = "Agent Usage Observer",
        [Str.UnexpectedError] = "Ocurrio un error inesperado:\n\n{0}",

        [Str.WindowConfigTitle] = "Agent Usage Observer",
        [Str.SettingsHeader] = "Configuracion",
        [Str.SectionRefresh] = "Actualizacion",
        [Str.PollIntervalLabel] = "Intervalo de consulta: ",
        [Str.PollIntervalHint] = "Cada cuanto se consulta el uso a los proveedores (60 a 900 s). Subir esto evita consultas innecesarias.",
        [Str.SectionIconColors] = "Colores del icono",
        [Str.UseServerSeverity] = "Usar la severidad que reporta el servidor",
        [Str.UseServerSeverityHint] = "Si esta activo, el color lo decide el proveedor; si no, usa los umbrales de abajo.",
        [Str.WarnFromLabel] = "Amarillo a partir de: ",
        [Str.CritFromLabel] = "Rojo a partir de: ",
        [Str.SectionSystem] = "Sistema",
        [Str.StartWithWindows] = "Iniciar con Windows",
        [Str.ButtonClose] = "Cerrar",
        [Str.ButtonSave] = "Guardar",

        [Str.MiniPanelTitle] = "Agentes",
        [Str.StatusNoSession] = "sin sesion",
        [Str.StatusNoConnection] = "sin conexion",
        [Str.StatusRateLimited] = "limite alcanzado",
        [Str.MsgSignIn] = "Inicia sesion en el proveedor.",
        [Str.MsgCouldNotFetch] = "No se pudo obtener el uso.",
        [Str.MsgRateLimitReached] = "Limite de uso alcanzado.",
        [Str.Updated] = "Actualizado {0}",
        [Str.OpenSettingsLink] = "Abrir configuracion",

        [Str.LabelFiveHour] = "Ultimas 5h",
        [Str.LabelWeek] = "Semana",
        [Str.ResetsSoon] = "Reinicia pronto",
        [Str.ResetsInDays] = "Reinicia en {0}d {1}h",
        [Str.ResetsInHours] = "Reinicia en {0}h {1}m",
        [Str.ResetsInMinutes] = "Reinicia en {0}m",

        [Str.TrayStartupTitle] = "Agent Usage Observer",
        [Str.TrayStartupMessage] = "Monitoreando el uso de agentes. Busca el icono en el area de notificaciones (flecha ^).",
        [Str.TooltipLoading] = "Cargando uso de agentes...",
        [Str.TooltipNoSession] = "Sin sesion",
        [Str.TooltipNoConnection] = "Sin conexion",
        [Str.TooltipFiveHour] = "5h {0}%",
        [Str.TooltipFiveHourEmpty] = "5h -",
        [Str.TooltipWeek] = "Semana {0}%",
        [Str.TooltipWeekEmpty] = "Semana -",
        [Str.TooltipWaiting] = " - esperando",
        [Str.MenuSettings] = "Configuracion...",
        [Str.MenuRefreshNow] = "Actualizar ahora",
        [Str.MenuExit] = "Salir",

        [Str.ProviderSignInClaudeCode] = "Inicia sesion en Claude Code (claude login).",
        [Str.ProviderSignInCodex] = "Inicia sesion en Codex.",
        [Str.ProviderSessionExpired] = "Sesion de Claude expirada. Reabre Claude Code.",
        [Str.ProviderRateLimitRetry] = "Limite de consultas alcanzado. Reintenta en {0}.",
        [Str.ProviderUsageQueryError] = "Error consultando uso ({0}).",
        [Str.ProviderNoConnection] = "Sin conexion con api.anthropic.com.",
        [Str.ProviderNoRecentUsageData] = "Todavia no hay datos recientes de uso de Codex. Inicia una sesion de Codex.",

        [Str.WaitSeconds] = "{0} s",
        [Str.WaitMinutes] = "{0} min",
        [Str.WaitHours] = "{0} h",

        [Str.UpdateAvailableTitle] = "Actualizacion disponible",
        [Str.UpdateAvailableMessage] = "Hay una version nueva: {0} (tenes la {1}).\n\nDescargarla e instalarla ahora?",
        [Str.UpdateButtonInstall] = "Instalar ahora",
        [Str.UpdateButtonLater] = "Despues",
        [Str.UpdateButtonSkip] = "Omitir esta version",
        [Str.UpdateDownloadError] = "No se pudo descargar la actualizacion:\n\n{0}",
    };

    public static readonly IReadOnlyDictionary<Str, string> Pt = new Dictionary<Str, string>
    {
        [Str.AppName] = "Agent Usage Observer",
        [Str.UnexpectedError] = "Ocorreu um erro inesperado:\n\n{0}",

        [Str.WindowConfigTitle] = "Agent Usage Observer",
        [Str.SettingsHeader] = "Configuracoes",
        [Str.SectionRefresh] = "Atualizacao",
        [Str.PollIntervalLabel] = "Intervalo de consulta: ",
        [Str.PollIntervalHint] = "Com que frequencia o uso e consultado nos provedores (60 a 900 s). Aumentar isto evita consultas desnecessarias.",
        [Str.SectionIconColors] = "Cores do icone",
        [Str.UseServerSeverity] = "Usar a severidade informada pelo servidor",
        [Str.UseServerSeverityHint] = "Se ativo, a cor e definida pelo provedor; caso contrario, usa os limites abaixo.",
        [Str.WarnFromLabel] = "Amarelo a partir de: ",
        [Str.CritFromLabel] = "Vermelho a partir de: ",
        [Str.SectionSystem] = "Sistema",
        [Str.StartWithWindows] = "Iniciar com o Windows",
        [Str.ButtonClose] = "Fechar",
        [Str.ButtonSave] = "Salvar",

        [Str.MiniPanelTitle] = "Agentes",
        [Str.StatusNoSession] = "sem sessao",
        [Str.StatusNoConnection] = "sem conexao",
        [Str.StatusRateLimited] = "limite atingido",
        [Str.MsgSignIn] = "Faca login no provedor.",
        [Str.MsgCouldNotFetch] = "Nao foi possivel obter o uso.",
        [Str.MsgRateLimitReached] = "Limite de uso atingido.",
        [Str.Updated] = "Atualizado {0}",
        [Str.OpenSettingsLink] = "Abrir configuracoes",

        [Str.LabelFiveHour] = "Ultimas 5h",
        [Str.LabelWeek] = "Semana",
        [Str.ResetsSoon] = "Reinicia em breve",
        [Str.ResetsInDays] = "Reinicia em {0}d {1}h",
        [Str.ResetsInHours] = "Reinicia em {0}h {1}m",
        [Str.ResetsInMinutes] = "Reinicia em {0}m",

        [Str.TrayStartupTitle] = "Agent Usage Observer",
        [Str.TrayStartupMessage] = "Monitorando o uso dos agentes. Procure o icone na area de notificacao (seta ^).",
        [Str.TooltipLoading] = "Carregando uso dos agentes...",
        [Str.TooltipNoSession] = "Sem sessao",
        [Str.TooltipNoConnection] = "Sem conexao",
        [Str.TooltipFiveHour] = "5h {0}%",
        [Str.TooltipFiveHourEmpty] = "5h -",
        [Str.TooltipWeek] = "Semana {0}%",
        [Str.TooltipWeekEmpty] = "Semana -",
        [Str.TooltipWaiting] = " - aguardando",
        [Str.MenuSettings] = "Configuracoes...",
        [Str.MenuRefreshNow] = "Atualizar agora",
        [Str.MenuExit] = "Sair",

        [Str.ProviderSignInClaudeCode] = "Faca login no Claude Code (claude login).",
        [Str.ProviderSignInCodex] = "Faca login no Codex.",
        [Str.ProviderSessionExpired] = "Sessao do Claude expirada. Reabra o Claude Code.",
        [Str.ProviderRateLimitRetry] = "Limite de consultas atingido. Tente novamente em {0}.",
        [Str.ProviderUsageQueryError] = "Erro ao consultar o uso ({0}).",
        [Str.ProviderNoConnection] = "Sem conexao com api.anthropic.com.",
        [Str.ProviderNoRecentUsageData] = "Ainda nao ha dados recentes de uso do Codex. Inicie uma sessao do Codex.",

        [Str.WaitSeconds] = "{0} s",
        [Str.WaitMinutes] = "{0} min",
        [Str.WaitHours] = "{0} h",

        [Str.UpdateAvailableTitle] = "Atualizacao disponivel",
        [Str.UpdateAvailableMessage] = "Ha uma versao nova: {0} (voce tem a {1}).\n\nBaixar e instalar agora?",
        [Str.UpdateButtonInstall] = "Instalar agora",
        [Str.UpdateButtonLater] = "Depois",
        [Str.UpdateButtonSkip] = "Ignorar esta versao",
        [Str.UpdateDownloadError] = "Nao foi possivel baixar a atualizacao:\n\n{0}",
    };
}
